[package]
name = "structstruck"
authors = ["Julius Michaelis <gitter@liftm.de>"]
license = "MIT"
categories = ["rust-patterns", "development-tools::procedural-macro-helpers"]
keywords = ["proc_macro", "nested", "struct"]
version = "0.1.0"
edition = "2021"
description = "Nested struct and enum definitions"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.5.0"
proc-macro2 = "1.0.37"
quote = "1.0.17"
venial = { git = "https://github.com/PoignardAzur/venial", rev = "436701c08c513a008a1080964a7d6b407af1e158" }
